# Generated by Django 3.0.3 on 2020-03-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='published',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='published_time',
        ),
    ]
