# Generated by Django 3.0.3 on 2020-03-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_auto_20200312_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPageNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Kategori')),
            ],
        ),
        migrations.AddField(
            model_name='staticpage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticpages.StaticPageNav'),
            preserve_default=False,
        ),
    ]
