# Generated by Django 3.1.13 on 2022-02-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_auto_20200716_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='members_only',
            field=models.BooleanField(default=False, verbose_name='Kräv inloggning'),
        ),
    ]
