# Generated by Django 4.2.11 on 2024-03-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0003_staticpage_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpagenav',
            name='category_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='staticpagenav',
            name='category_name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='staticpagenav',
            name='category_name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='staticurl',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='staticurl',
            name='title_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='staticurl',
            name='title_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Titel'),
        ),
    ]
