# Generated by Django 5.0.14 on 2025-10-31 16:56

from django.db import migrations, models

def migrate_staticpage_menu_entries(apps, schema_editor):
    StaticPage = apps.get_model('staticpages', 'StaticPage')
    StaticUrl = apps.get_model('staticpages', 'StaticUrl')

    for page in StaticPage.objects.exclude(category__isnull=True):
        category_id = page.category_id
        if category_id is None:
            continue

        target_url = f'/pages/{page.slug}/'
        target_dropdown = page.dropdown_element or 0

        link, created = StaticUrl.objects.get_or_create(
            category_id=category_id,
            url=target_url,
            defaults={
                'title': page.title,
                'dropdown_element': target_dropdown,
                'logged_in_only': page.members_only,
            },
        )

        if created:
            continue

        update_fields = []
        if link.title != page.title:
            link.title = page.title
            update_fields.append('title')
        if link.dropdown_element != target_dropdown:
            link.dropdown_element = target_dropdown
            update_fields.append('dropdown_element')
        if link.logged_in_only != page.members_only:
            link.logged_in_only = page.members_only
            update_fields.append('logged_in_only')

        if update_fields:
            link.save(update_fields=update_fields)

class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0003_alter_staticpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpagenav',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='staticpagenav',
            name='use_category_url',
            field=models.BooleanField(default=False, verbose_name='Använd kategorins URL'),
        ),
        migrations.AddField(
            model_name='staticurl',
            name='logged_in_only',
            field=models.BooleanField(default=False, verbose_name='Visa endast åt inloggade användare'),
        ),
        migrations.AlterField(
            model_name='staticurl',
            name='dropdown_element',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='#'),
        ),
        migrations.RunPython(migrate_staticpage_menu_entries, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='staticpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='dropdown_element',
        ),
    ]
