# Generated by Django 5.0.3 on 2024-03-26 22:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0003_staticpage_members_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Innehåll'),
        ),
    ]
