# Generated by Django 5.0.9 on 2024-12-19 17:54

from django.db import migrations
from django.urls import reverse


def change_nav_to_url(apps, schema_editor):
    StaticPage = apps.get_model('staticpages', 'StaticPage')
    StaticUrl = apps.get_model('staticpages', 'StaticUrl')

    all_pages = StaticPage.objects.filter(category__isnull=False)

    for page in all_pages:
        category = page.category
        idx = page.dropdown_element
        url = reverse("staticpages:page", args=[page.slug])
        nav_url = StaticUrl(title=page.title, url=url, category=category, dropdown_element=idx)
        nav_url.save()

        page.category = None
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0004_alter_staticpage_content'),
    ]

    operations = [
        migrations.RunPython(change_nav_to_url),
    ]
