# Generated by Django 5.0.3 on 2024-03-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0004_alter_staticpage_content'),
        ('staticpages', '0004_staticpagenav_category_name_en_and_more'),
    ]

    operations = [
    ]
