# Generated by Django 5.0.9 on 2024-12-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0005_auto_20241219_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='dropdown_element',
        ),
        migrations.AddField(
            model_name='staticpagenav',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='staticpagenav',
            name='use_category_url',
            field=models.BooleanField(default=False, verbose_name='Använd kategorins URL'),
        ),
        migrations.AddField(
            model_name='staticurl',
            name='logged_in_only',
            field=models.BooleanField(default=False, verbose_name='Visa endast åt inloggade användare'),
        ),
        migrations.AlterField(
            model_name='staticurl',
            name='dropdown_element',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='#'),
        ),
    ]
