# Generated by Django 5.0.4 on 2026-05-02 01:40

import archive.fields
import core.storage_backends
from django.db import migrations, models
import staticpages.models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0008_staticurl_logged_in_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=staticpages.models.upload_to, verbose_name='Bakgrundsbild'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='s3_image',
            field=archive.fields.PublicFileField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to=staticpages.models.upload_to, verbose_name='Bakgrundsbild'),
        ),
    ]
