# Generated by Django 5.2.10 on 2026-01-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0008_staticurl_logged_in_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpagenav',
            name='category_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='staticpagenav',
            name='category_name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='staticpagenav',
            name='category_name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='staticurl',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='staticurl',
            name='title_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='staticurl',
            name='title_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Titel'),
        ),
    ]
