# Generated by Django 5.2.12 on 2026-04-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0011_staticpage_title_content_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticurl',
            options={'ordering': ['dropdown_element']},
        ),
    ]
