# Generated by Django 5.2.12 on 2026-05-02 01:40

from django.db import migrations, models

import core.fields
import staticpages.models


class Migration(migrations.Migration):
    dependencies = [
        ("staticpages", "0012_alter_staticurl_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=staticpages.models.upload_to, verbose_name="Bakgrundsbild"
            ),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="s3_image",
            field=core.fields.PublicFileField(
                blank=True, null=True, upload_to=staticpages.models.upload_to, verbose_name="Bakgrundsbild"
            ),
        ),
    ]
