# Generated by Django 3.0.7 on 2021-01-26 12:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Innehåll')),
            ],
            options={
                'verbose_name': 'fromellt evenemang',
                'verbose_name_plural': 'formella evenemang',
                'ordering': ('id',),
            },
        ),
    ]
