# Generated by Django 2.1.15 on 2020-01-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sign_up_cancelling_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Avanmälningen stängs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sign_up_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Anmälningen stängs'),
        ),
    ]
