# Generated by Django 6.0.5 on 2026-05-11 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examfile',
            options={'ordering': ('title', 'id'), 'verbose_name': 'tentamen', 'verbose_name_plural': 'tentamina'},
        ),
        migrations.AlterField(
            model_name='examarchive',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
