# Generated by Django 2.1.15 on 2020-01-09 17:09

import ckeditor.fields
import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Innehåll')),
                ('event_date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Startdatum')),
                ('event_date_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Slutdatum')),
                ('sign_up_max_participants', models.IntegerField(choices=[(0, 'Ingen begränsning'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109), (110, 110), (111, 111), (112, 112), (113, 113), (114, 114), (115, 115), (116, 116), (117, 117), (118, 118), (119, 119), (120, 120), (121, 121), (122, 122), (123, 123), (124, 124), (125, 125), (126, 126), (127, 127), (128, 128), (129, 129), (130, 130), (131, 131), (132, 132), (133, 133), (134, 134), (135, 135), (136, 136), (137, 137), (138, 138), (139, 139), (140, 140), (141, 141), (142, 142), (143, 143), (144, 144), (145, 145), (146, 146), (147, 147), (148, 148), (149, 149), (150, 150), (151, 151), (152, 152), (153, 153), (154, 154), (155, 155), (156, 156), (157, 157), (158, 158), (159, 159), (160, 160), (161, 161), (162, 162), (163, 163), (164, 164), (165, 165), (166, 166), (167, 167), (168, 168), (169, 169), (170, 170), (171, 171), (172, 172), (173, 173), (174, 174), (175, 175), (176, 176), (177, 177), (178, 178), (179, 179), (180, 180), (181, 181), (182, 182), (183, 183), (184, 184), (185, 185), (186, 186), (187, 187), (188, 188), (189, 189), (190, 190), (191, 191), (192, 192), (193, 193), (194, 194), (195, 195), (196, 196), (197, 197), (198, 198), (199, 199)], default=0, verbose_name='Maximal antal deltagare')),
                ('sign_up', models.BooleanField(default=True, verbose_name='Anmälning')),
                ('sign_up_members', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Anmälan öppnas (medlemmar)')),
                ('sign_up_others', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Anmälan öppnas (övriga)')),
                ('sign_up_deadline', models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 16, 17, 9, 15, 577221, tzinfo=utc), null=True, verbose_name='Anmälningen stängs')),
                ('sign_up_cancelling', models.BooleanField(default=True, verbose_name='Avanmälning')),
                ('sign_up_cancelling_deadline', models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 14, 17, 9, 15, 577323, tzinfo=utc), null=True, verbose_name='Avanmälningen stängs')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Skapad')),
                ('published_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Publicerad')),
                ('modified_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modifierad')),
                ('published', models.BooleanField(default=True, verbose_name='Publicera')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evenemang',
                'verbose_name_plural': 'evenemang',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventAttendees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_nr', models.PositiveSmallIntegerField(verbose_name='#')),
                ('user', models.CharField(max_length=255, verbose_name='Namn')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-postadress')),
                ('preferences', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Svar')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Anonymt')),
                ('time_registered', models.DateTimeField(verbose_name='Registrerad')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'deltagare',
                'verbose_name_plural': 'deltagare',
                'ordering': ['time_registered'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Namn')),
                ('type', models.CharField(blank=True, choices=[('text', 'Text'), ('select', 'Multiple choice'), ('checkbox', 'Kryssryta')], max_length=255, null=True, verbose_name='Typ')),
                ('required', models.BooleanField(default=False, verbose_name='Krävd')),
                ('published', models.BooleanField(default=True, verbose_name='Visa')),
                ('public_info', models.BooleanField(default=False, verbose_name='Öppen info')),
                ('choice_list', models.CharField(blank=True, max_length=255, verbose_name='Alternativ')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Anmälningsfält',
                'verbose_name_plural': 'Anmälningsfält',
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventattendees',
            unique_together={('event', 'email')},
        ),
    ]
