# Generated by Django 3.1.13 on 2022-08-20 18:02

import archive.fields
import core.storage_backends
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200116_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistrationform',
            name='published',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.upload_to, verbose_name='Bakgrundsbild'),
        ),
        migrations.AddField(
            model_name='event',
            name='members_only',
            field=models.BooleanField(default=False, verbose_name='Kräv inloggning för innehåll'),
        ),
        migrations.AddField(
            model_name='event',
            name='passcode',
            field=models.CharField(blank=True, max_length=255, verbose_name='Passcode'),
        ),
        migrations.AddField(
            model_name='event',
            name='s3_image',
            field=archive.fields.PublicFileField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to=events.models.upload_to, verbose_name='Bakgrundsbild'),
        ),
        migrations.AddField(
            model_name='event',
            name='sign_up_avec',
            field=models.BooleanField(default=False, verbose_name='Avec'),
        ),
        migrations.AddField(
            model_name='eventattendees',
            name='avec_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventattendees', verbose_name='Avec till'),
        ),
        migrations.AddField(
            model_name='eventregistrationform',
            name='hide_for_avec',
            field=models.BooleanField(default=False, verbose_name='Göm för avec'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sign_up_cancelling_deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Avanmälningen stängs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sign_up_deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Anmälningen stängs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='eventattendees',
            name='preferences',
            field=models.JSONField(blank=True, default=list, verbose_name='Svar'),
        ),
    ]
