# Generated by Django 3.1.13 on 2022-02-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200331_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sign_up_avec',
            field=models.BooleanField(default=False, verbose_name='Avec'),
        ),
        migrations.AddField(
            model_name='eventattendees',
            name='avec_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventattendees', verbose_name='Avec till'),
        ),
        migrations.AddField(
            model_name='eventregistrationform',
            name='hide_for_avec',
            field=models.BooleanField(default=False, verbose_name='Göm för avec'),
        ),
        migrations.AlterField(
            model_name='eventattendees',
            name='preferences',
            field=models.JSONField(blank=True, default=list, verbose_name='Svar'),
        ),
    ]
