# Generated by Django 3.1.13 on 2022-03-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220225_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members_only',
            field=models.BooleanField(default=False, verbose_name='Kräv inloggning för innehåll'),
        ),
    ]
