# Generated by Django 4.2.9 on 2024-01-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='redirect_link',
            field=models.URLField(blank=True, verbose_name='Redirect Link'),
        ),
        migrations.AddField(
            model_name='eventregistrationform',
            name='choice_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='#'),
        ),
    ]
