# Generated by Django 3.1.13 on 2022-05-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='passcode',
            field=models.CharField(blank=True, max_length=255, verbose_name='Passcode'),
        ),
    ]
