# Generated by Django 3.1.13 on 2022-08-18 16:48

import archive.fields
import core.storage_backends
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.upload_to, verbose_name='Bakgrundsbild'),
        ),
        migrations.AddField(
            model_name='event',
            name='passcode',
            field=models.CharField(blank=True, max_length=255, verbose_name='Passcode'),
        ),
        migrations.AddField(
            model_name='event',
            name='s3_image',
            field=archive.fields.PublicFileField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to=events.models.upload_to, verbose_name='Bakgrundsbild'),
        ),
    ]
