# Generated by Django 3.1.13 on 2023-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20221004_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistrationform',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pris'),
        ),
    ]
