# Generated by Django 4.1.7 on 2023-03-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventregistrationform_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendees',
            name='attendee_nr',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='#'),
        ),
    ]
