# Generated by Django 5.0.9 on 2025-03-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_sign_up_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sign_up_max_participants',
            field=models.IntegerField(default=0, verbose_name='Maximal antal deltagare (0 för ingen begränsning)'),
        ),
    ]
