# Generated by Django 5.0.14 on 2025-10-31 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_sign_up_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventattendees',
            name='original_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_event', to='events.event', verbose_name='Ursprungligt evenemang'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sign_up_max_participants',
            field=models.IntegerField(default=0, verbose_name='Maximal antal deltagare (0 för ingen begränsning)'),
        ),
    ]
