# Generated by Django 4.2.7 on 2023-11-13 17:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventattendees_attendee_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content_sv',
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name='Innehåll'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_en',
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name='Innehåll'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_fi',
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name='Innehåll'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_sv',
            field=models.CharField(
                max_length=255, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(
                max_length=255, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_fi',
            field=models.CharField(
                max_length=255, null=True, verbose_name='Titel'),
        ),
    ]
