# Generated by Django 4.1.7 on 2023-04-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventattendees_attendee_nr'),
        ('events', '0009_event_price'),
    ]

    operations = [
    ]
