# Generated by Django 4.2.7 on 2023-11-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_content_af_event_content_ar_and_more'),
    ]

    operations = [
    ]
