# Generated by Django 4.2.7 on 2023-11-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='redirect_link',
            field=models.URLField(blank=True, verbose_name='Redirect Link'),
        ),
    ]
