# Generated by Django 4.2.9 on 2024-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_captcha_alter_event_sign_up_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistrationform',
            name='choice_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='#'),
        ),
    ]
