# Generated by Django 5.0.2 on 2024-03-03 20:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventregistrationform_choice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Innehåll'),
        ),
    ]
