# Generated by Django 4.2.9 on 2024-01-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventregistrationform_choice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='redirect_link',
            field=models.URLField(blank=True, verbose_name='Redirect Link'),
        ),
    ]
