# Generated by Django 5.0.3 on 2024-03-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_content_af_remove_event_content_ar_and_more'),
        ('events', '0013_alter_event_content'),
    ]

    operations = [
    ]
