# Generated by Django 5.0.10 on 2024-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='eventregistrationform',
            name='price',
        ),
        migrations.AlterField(
            model_name='event',
            name='sign_up_max_participants',
            field=models.IntegerField(default=0, verbose_name='Maximal antal deltagare (0 för ingen begränsning)'),
        ),
    ]
