# Generated by Django 5.2.3 on 2025-06-10 21:45

from django.db import migrations, models


def populate_event_templates(apps, _):
    """Populate the new template field for previously hard coded overrides."""
    Event = apps.get_model("events", "Event")  # noqa

    title_map = {
        "årsfest": "events/custom/arsfest.html",
        "årsfest gäster": "events/custom/arsfest.html",
        "100 baal": "events/custom/kk100_detail.html",
        "baal": "events/custom/baal_detail.html",
        "tomtejakt": "events/custom/tomtejakt.html",
        "wappmiddag": "events/custom/wappmiddag.html",
    }
    slug_map = {
        "baal": "events/custom/baal_detail.html",
        "tomtejakt": "events/custom/tomtejakt.html",
        "wappmiddag": "events/custom/wappmiddag.html",
        "arsfest": "events/custom/arsfest.html",
        "arsfest_stipendiater": "events/custom/arsfest.html",
    }

    for event in Event.objects.all():
        title_key = event.title.lower()
        if title_key in title_map:
            event.template = title_map[title_key]
            event.save()
            continue
        if event.slug in slug_map:
            event.template = slug_map[event.slug]
            event.save()



class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_alter_event_sign_up_max_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="template",
            field=models.CharField(
                default="events/detail.html", max_length=255, verbose_name="Template"
            ),
        ),
        migrations.RunPython(populate_event_templates),
    ]
