# Generated by Django 5.0.3 on 2024-03-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_merge_20240325_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, verbose_name='Innehåll'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Innehåll'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Innehåll'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Innehåll'),
        ),
    ]
