# Generated by Django 5.0.3 on 2024-03-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_content_af_event_content_ar_and_more'),
        ('events', '0015_alter_event_content_alter_event_content_en_and_more'),
    ]

    operations = [
    ]
