# Generated by Django 5.2.10 on 2026-01-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_parent_eventattendees_original_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Innehåll'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Innehåll'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Innehåll'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, verbose_name='Innehåll'),
        ),
    ]
