# Generated by Django 5.2.12 on 2026-04-07 17:40

import core.fields
import events.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_backfill_event_default_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='s3_image',
            field=core.fields.PublicFileField(blank=True, null=True, upload_to=events.models.upload_to, verbose_name='Bakgrundsbild'),
        ),
    ]
