# Generated by Django 6.0.7 on 2026-08-27 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_remove_event_published_alter_event_published_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['published_time', 'event_date_end'], name='event_pub_end_idx'),
        ),
    ]
