# Generated by Django 6.0.7 on 2026-08-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_event_pub_end_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventattendees',
            constraint=models.UniqueConstraint(fields=('event', 'attendee_nr'), name='unique_attendee_nr_per_event'),
        ),
    ]
