# Generated by Django 6.0.7 on 2026-08-31 23:40

from django.db import migrations, models


def repair_duplicate_attendee_nrs(apps, schema_editor):
    # The pre-constraint max+10 allocation was an unlocked read for events
    # that skip the row lock, so production data can already hold duplicate
    # (event, attendee_nr) values that would make AddConstraint fail. Walk
    # each event's attendees in display order and move repeated numbers to
    # the next free step-10 slot. Near the smallint ceiling the step-10 space
    # above runs out, so the whole event is compacted into a fresh monotonic
    # sequence (10, 20, ...), preserving display order at the cost of
    # renumbering the event. An event with more attendees than step-10 slots
    # (3276) cannot be repaired and fails loudly instead of writing numbers
    # outside the valid smallint range.
    #
    # This data repair is not reversible: reversed migrations leave the
    # renumbered/compacted values in place (the reverse operation is noop).
    #
    # The repair and the AddConstraint below must be atomic against live
    # signups. Migrations run in one transaction on PostgreSQL, so taking an
    # ACCESS EXCLUSIVE lock on the attendee table here is held until the
    # migration commits, and no signup can insert a duplicate between the
    # last repair UPDATE and the constraint becoming active; signups queue up
    # behind the lock and resume once the constraint exists. Plan a low
    # traffic window: the lock blocks all writes for the duration. SQLite
    # serializes whole-database writes on its own, so it needs no explicit
    # lock.
    EventAttendees = apps.get_model('events', 'EventAttendees')
    Event = apps.get_model('events', 'Event')
    connection = schema_editor.connection
    db_alias = connection.alias
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            cursor.execute('LOCK TABLE events_eventattendees IN ACCESS EXCLUSIVE MODE')
    for event in Event.objects.using(db_alias).all():
        attendees = list(EventAttendees.objects.using(db_alias).filter(event=event).order_by('attendee_nr', 'pk'))
        seen = set()
        last_nr = -1
        renumbered = []
        for attendee in attendees:
            nr = attendee.attendee_nr
            if nr is not None and nr not in seen and nr > last_nr:
                seen.add(nr)
                last_nr = nr
                continue
            last_nr += 10
            while last_nr in seen:
                last_nr += 10
            if last_nr > 32767:
                if len(attendees) > 3276:
                    raise RuntimeError(
                        f'Cannot repair attendee numbers for event {event.pk}: '
                        f'{len(attendees)} attendees exceed the step-10 smallint space'
                    )
                renumbered = [
                    EventAttendees(pk=row.pk, attendee_nr=(index + 1) * 10) for index, row in enumerate(attendees)
                ]
                break
            seen.add(last_nr)
            renumbered.append(EventAttendees(pk=attendee.pk, attendee_nr=last_nr))
        if renumbered:
            EventAttendees.objects.using(db_alias).bulk_update(renumbered, ['attendee_nr'])


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0024_event_event_pub_end_idx'),
    ]

    operations = [
        migrations.RunPython(repair_duplicate_attendee_nrs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='eventattendees',
            constraint=models.UniqueConstraint(fields=('event', 'attendee_nr'), name='unique_attendee_nr_per_event'),
        ),
    ]
