# Generated by Django 6.0.7 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0025_eventattendees_unique_attendee_nr_per_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee_nr_counter',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='eventattendees',
            name='attendee_nr',
            field=models.PositiveBigIntegerField(blank=True, verbose_name='#'),
        ),
    ]
