# Generated by Django 5.1.4 on 2025-01-12 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0014_alter_event_sign_up_max_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBillingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('integration_type', models.IntegerField()),
                ('price', models.CharField()),
                ('price_selector', models.CharField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(max_length=20)),
                ('reference_number', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventattendees')),
            ],
        ),
    ]
