# Generated by Django 5.1.4 on 2025-01-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvoice',
            name='invoice_number',
            field=models.IntegerField(),
        ),
    ]
