# Generated by Django 5.1.4 on 2025-01-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_eventinvoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvoice',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eventinvoice',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='eventinvoice',
            name='invoice_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='eventinvoice',
            name='reference_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
