# Generated by Django 5.2 on 2025-04-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=256)),
            ],
            options={
                'verbose_name': 'Emailmottagare för ÅAATK',
                'verbose_name_plural': 'Emailmottagare för ÅAATK',
            },
        ),
    ]
