services:
  db:
    restart: always
    expose:
      - ${DB_PORT}
    ports: !reset []

  web:
    image: ghcr.io/datateknologerna-vid-abo-akademi/date-website:${IMG_TAG}
    restart: always
    command: ./web.prod.sh
    expose:
      - ${WEB_PORT}
    ports: !reset []

  asgi:
    image: ghcr.io/datateknologerna-vid-abo-akademi/date-website:${IMG_TAG}
    restart: always
    command: /bin/bash -c "daphne -b 0.0.0.0 core.routing:application"
    expose:
      - ${WEB_PORT}
    env_file:
      - ${ENV_FILE}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    restart: always
    image: ghcr.io/datateknologerna-vid-abo-akademi/date-website:${IMG_TAG}
    env_file:
      - ${ENV_FILE}

  redis:
    restart: always
    expose:
      - ${REDIS_PORT}
    ports: !reset []
    
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - asgi
