version: '3'

services:
  db:
    image: postgres:${DATE_POSTGRESQL_VERSION}-alpine
    restart: always
    volumes:
      - date_postgres_data:/var/lib/postgresql/data/
    ports:
      - ${DATE_DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DATE_DB_PASSWORD}
    networks:
      - internal
  web:
    image: ghcr.io/datateknologerna-vid-abo-akademi/date-website:${DATE_IMG_TAG}
    restart: always
    command: /bin/bash -c "./wait-for-postgres.sh db:5432 && python /code/manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn -w 3 --max-requests 1000 --max-requests-jitter 100 --bind=0.0.0.0 core.wsgi"
    environment:
      - SECRET_KEY=${DATE_SECRET_KEY}
      - DEBUG=${DATE_DEBUG}
      - DEVELOP=${DATE_DEVELOP}
      - PROJECT_NAME=${PROJECT_NAME}
      - DB_PASSWORD=${DATE_DB_PASSWORD}
      - USE_S3=${USE_S3}
      - AWS_S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - AWS_STORAGE_BUCKET_NAME=${S3_BUCKET_NAME}
      - PUBLIC_MEDIA_LOCATION=${PUBLIC_MEDIA_LOCATION}
      - PRIVATE_MEDIA_LOCATION=${PRIVATE_MEDIA_LOCATION}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - EXTRA_STAFF_GROUPS=${EXTRA_STAFF_GROUPS}
      - EMAIL_HOST_RECEIVER=${EMAIL_HOST_RECEIVER}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - CF_TURNSTILE_SITE_KEY=${CF_TURNSTILE_SITE_KEY}
      - CF_TURNSTILE_SECRET_KEY=${CF_TURNSTILE_SECRET_KEY}
      - ALUMNI_SETTINGS=${ALUMNI_SETTINGS}
    depends_on:
      - db
      - redis
    networks:
      - internal
      - external
  asgi:
    image: ghcr.io/datateknologerna-vid-abo-akademi/date-website:${DATE_IMG_TAG}
    restart: always
    command: /bin/bash -c "./wait-for-postgres.sh db:5432 && daphne -b 0.0.0.0 core.routing:application"
    environment:
      - SECRET_KEY=${DATE_SECRET_KEY}
      - DEBUG=${DATE_DEBUG}
      - DEVELOP=${DATE_DEVELOP}
      - PROJECT_NAME=${PROJECT_NAME}
      - DB_PASSWORD=${DATE_DB_PASSWORD}
      - USE_S3=${USE_S3}
      - AWS_S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - AWS_STORAGE_BUCKET_NAME=${S3_BUCKET_NAME}
      - PUBLIC_MEDIA_LOCATION=${PUBLIC_MEDIA_LOCATION}
      - PRIVATE_MEDIA_LOCATION=${PRIVATE_MEDIA_LOCATION}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - EXTRA_STAFF_GROUPS=${EXTRA_STAFF_GROUPS}
      - EMAIL_HOST_RECEIVER=${EMAIL_HOST_RECEIVER}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - CF_TURNSTILE_SITE_KEY=${CF_TURNSTILE_SITE_KEY}
      - CF_TURNSTILE_SECRET_KEY=${CF_TURNSTILE_SECRET_KEY}
    depends_on:
      - db
      - redis
    networks:
      - internal
      - external
  celery:
    restart: always
    image: ghcr.io/datateknologerna-vid-abo-akademi/date-website:${DATE_IMG_TAG}
    command: celery -A core worker -l info -c 2
    environment:
      - DEBUG=${DATE_DEBUG}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - ALUMNI_SETTINGS=${ALUMNI_SETTINGS}
    depends_on:
      - db
      - redis
    networks:
        - internal
  redis:
    restart: always
    image: valkey/valkey:7.2-alpine
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - internal
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - ${DATE_DJANGO_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - external
    depends_on:
      - web
      - asgi

volumes:
  date_postgres_data:

networks:
    internal:
    external:

