# Generated by Django 2.1.1 on 2018-09-12 10:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Innehåll')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Skapad')),
                ('published_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Publicerad')),
                ('modified_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modifierad')),
                ('published', models.BooleanField(default=True, verbose_name='Publicera')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nyhet',
                'verbose_name_plural': 'nyheter',
                'ordering': ('id',),
            },
        ),
    ]
