# Generated by Django 5.0.3 on 2024-04-01 16:38

import django.db.models.deletion
from django.db import migrations, models


def populate_aa_category(apps, _):
    Category = apps.get_model('news', 'Category')  # noqa
    Post = apps.get_model('news', 'Post')  # noqa

    aa_objects = Post.objects.filter(albins_angels=True)
    if len(aa_objects) == 0:
        return
    aa_category = Category.objects.create(name='Albins Angels', slug='albins-angels')
    for post in aa_objects:
        post.category = aa_category
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Namn')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'kategori',
                'verbose_name_plural': 'kategorier',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Kategori'),
        ),
        migrations.RunPython(populate_aa_category),
    ]
