# Generated by Django 6.0.7 on 2026-08-27 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_post_published_alter_post_published_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'published_time'], name='post_cat_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['published_time'], name='post_pub_idx'),
        ),
    ]
