# Generated by Django 5.1.4 on 2025-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbillingconfiguration',
            name='price_selector',
            field=models.CharField(blank=True, null=True),
        ),
    ]
