# Generated by Django 5.2.12 on 2026-03-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseclaim',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Kontant'), ('bank', 'Banköverföring')], max_length=4),
        ),
    ]
