# Generated by Django 5.2.12 on 2026-03-25 15:40

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenseclaim_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereceipt',
            name='file',
            field=models.FileField(upload_to=expenses.models.receipt_upload_to),
        ),
    ]
