# Generated by Django 5.2.1 on 2025-09-14 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTKeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this key pair', max_length=100, unique=True)),
                ('private_key_pem', models.TextField(help_text='PEM encoded private key')),
                ('public_key_pem', models.TextField(help_text='PEM encoded public key')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this key pair is active for signing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for key rotation', null=True)),
            ],
            options={
                'verbose_name': 'JWT Key Pair',
                'verbose_name_plural': 'JWT Key Pairs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JWTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('purpose', models.CharField(blank=True, help_text='Purpose/scope of the token', max_length=100)),
                ('key_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.jwtkeypair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jwt_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JWT Token',
                'verbose_name_plural': 'JWT Tokens',
                'ordering': ['-issued_at'],
            },
        ),
    ]
