# Generated by Django 5.2.1 on 2025-09-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Scope name (e.g., 'base', 'image_upload')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description of what this scope allows')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'JWT Scope',
                'verbose_name_plural': 'JWT Scopes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='jwttoken',
            name='purpose',
            field=models.CharField(blank=True, help_text='Purpose/description of the token', max_length=100),
        ),
        migrations.AddField(
            model_name='jwttoken',
            name='scopes',
            field=models.ManyToManyField(blank=True, to='jwt_auth.jwtscope'),
        ),
    ]
