# Generated by Django 6.0.7 on 2026-09-13 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEmailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=320, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Mottagare för feedback',
                'verbose_name_plural': 'Mottagare för feedback',
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('message', models.TextField(max_length=1500, verbose_name='Meddelande')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Skickad')),
            ],
            options={
                'verbose_name': 'Inskickad feedback',
                'verbose_name_plural': 'Inskickad feedback',
                'ordering': ('-created_time',),
            },
        ),
    ]
