# Generated by Django 6.0.7 on 2026-10-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFormSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.CharField(blank=True, default='', help_text='Texten som visas ovanför formuläret på /forms/.', max_length=500, verbose_name='Introduktionstext')),
                ('intro_text_sv', models.CharField(blank=True, default='', help_text='Texten som visas ovanför formuläret på /forms/.', max_length=500, null=True, verbose_name='Introduktionstext')),
                ('intro_text_en', models.CharField(blank=True, default='', help_text='Texten som visas ovanför formuläret på /forms/.', max_length=500, null=True, verbose_name='Introduktionstext')),
                ('intro_text_fi', models.CharField(blank=True, default='', help_text='Texten som visas ovanför formuläret på /forms/.', max_length=500, null=True, verbose_name='Introduktionstext')),
            ],
            options={
                'verbose_name': 'Formulärtext',
                'verbose_name_plural': 'Formulärtext',
            },
        ),
    ]
