# Generated by Django 5.2.7 on 2025-10-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipSignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Fullständigt namn')),
                ('birth_date', models.DateField(verbose_name='Födelsedag (ÅÅÅÅ-MM-DD)')),
                ('matriculation_number', models.CharField(max_length=20, verbose_name='Matrikelnummer')),
                ('street_address', models.CharField(max_length=100, verbose_name='Gatuadress')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postnummer')),
                ('city', models.CharField(max_length=50, verbose_name='Postort')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Telefonnummer')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Post')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Hemsida')),
                ('next_of_kin', models.CharField(max_length=200, verbose_name='Närmaste anhörig (Namn + telefonnummer)')),
                ('processor_speed', models.CharField(max_length=50, verbose_name='Processorhastighet')),
                ('willing_to_work', models.BooleanField()),
                ('newsletter_consent', models.BooleanField()),
                ('personal_data_sharing_nonconsent', models.BooleanField()),
                ('membership_type', models.CharField(choices=[('ordinary', 'Ordinarie medlem'), ('supporting', 'Stödjande medlem')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
