{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "date-website.postgresql.fullname" . }}
  labels:
    {{- include "date-website.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "date-website.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
