{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "date-website.fullname" . }}
  labels:
    {{- include "date-website.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.django.secretKey | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  AWS_ACCESS_KEY_ID: {{- if .Values.media.s3.enabled }} {{ required "media.s3.accessKeyId is required when media.s3.enabled=true" .Values.media.s3.accessKeyId | quote }}{{ else }} {{ .Values.media.s3.accessKeyId | quote }}{{ end }}
  AWS_SECRET_ACCESS_KEY: {{- if .Values.media.s3.enabled }} {{ required "media.s3.secretAccessKey is required when media.s3.enabled=true" .Values.media.s3.secretAccessKey | quote }}{{ else }} {{ .Values.media.s3.secretAccessKey | quote }}{{ end }}
  OBJECT_STORAGE_ACCESS_KEY_ID: {{- if .Values.backups.objectStorage.enabled }} {{ required "backups.objectStorage.accessKeyId is required when backups.objectStorage.enabled=true" .Values.backups.objectStorage.accessKeyId | quote }}{{ else }} {{ .Values.backups.objectStorage.accessKeyId | quote }}{{ end }}
  OBJECT_STORAGE_SECRET_ACCESS_KEY: {{- if .Values.backups.objectStorage.enabled }} {{ required "backups.objectStorage.secretAccessKey is required when backups.objectStorage.enabled=true" .Values.backups.objectStorage.secretAccessKey | quote }}{{ else }} {{ .Values.backups.objectStorage.secretAccessKey | quote }}{{ end }}
  EMAIL_HOST_USER: {{ .Values.email.username | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.email.password | quote }}
  CF_TURNSTILE_SECRET_KEY: {{ .Values.django.turnstile.secretKey | quote }}
{{- end }}
