# Generated by Django 6.0.7 on 2026-10-03 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'code_instructions',
                    models.TextField(
                        blank=True,
                        help_text='Visas offentligt där koden efterfrågas, i stället för standardtexten. Lämna tomt om standardtexten räcker.',
                        verbose_name='Så får besökare koden',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Bokningsinställningar',
                'verbose_name_plural': 'Bokningsinställningar',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Namn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                (
                    'code_generation',
                    models.PositiveIntegerField(
                        default=1,
                        editable=False,
                        help_text='Räknas upp varje gång utrymmets kod byts. Koden härleds ur den och kan inte läsas av härifrån.',
                        verbose_name='Kodgeneration',
                    ),
                ),
                (
                    'rotated_at',
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text='När utrymmets kod senast byttes. Gör att den förra koden fungerar en stund till.',
                        null=True,
                        verbose_name='Senast bytt',
                    ),
                ),
                (
                    'bookable_from',
                    models.TimeField(
                        blank=True,
                        help_text='Lämna båda tomma för att tillåta bokning dygnet runt. Med tider gäller de varje dag.',
                        null=True,
                        verbose_name='Bokningsbart från',
                    ),
                ),
                (
                    'bookable_until',
                    models.TimeField(
                        blank=True,
                        help_text='En bokning måste börja och sluta inom samma dygn när tider är satta.',
                        null=True,
                        verbose_name='Bokningsbart till',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Utrymme',
                'verbose_name_plural': 'Utrymmen',
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Stängt från')),
                ('end', models.DateTimeField(verbose_name='Stängt till')),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        help_text='Visas för besökare, till exempel vad som gör att utrymmet är stängt.',
                        max_length=255,
                        verbose_name='Beskrivning',
                    ),
                ),
                (
                    'room',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='closures',
                        to='booking.room',
                        verbose_name='Utrymme',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Stängd period',
                'verbose_name_plural': 'Stängda perioder',
                'ordering': ('start', 'pk'),
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('end__gt', models.F('start'))), name='closure_end_after_start'
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_name', models.CharField(blank=True, max_length=255, verbose_name='Namn')),
                ('booker_email', models.EmailField(blank=True, max_length=254, verbose_name='E-post')),
                ('start', models.DateTimeField(verbose_name='Starttid')),
                ('end', models.DateTimeField(verbose_name='Sluttid')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='Beskrivning')),
                (
                    'created',
                    models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Skapad'),
                ),
                (
                    'author',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='room_bookings',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Bokare',
                    ),
                ),
                (
                    'room',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bookings',
                        to='booking.room',
                        verbose_name='Utrymme',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Bokning',
                'verbose_name_plural': 'Bokningar',
                'ordering': ('start', 'pk'),
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('end__gt', models.F('start'))), name='booking_end_after_start'
                    )
                ],
            },
        ),
    ]
