# Generated by Django 6.0.7 on 2026-09-29 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_period', models.CharField(choices=[('daily', 'Dagligen'), ('weekly', 'Veckovis'), ('monthly', 'Månadsvis')], default='weekly', help_text='Hur ofta bokningskoden byts ut. Koden genereras automatiskt och kan inte ställas in manuellt.', max_length=8, verbose_name='Kodens rotationsperiod')),
            ],
            options={
                'verbose_name': 'Bokningsinställningar',
                'verbose_name_plural': 'Bokningsinställningar',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Namn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('is_active', models.BooleanField(default=True, help_text='Endast aktiva utrymmen visas för besökare på webbplatsen.', verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Utrymme',
                'verbose_name_plural': 'Utrymmen',
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_name', models.CharField(blank=True, max_length=255, verbose_name='Namn')),
                ('booker_email', models.EmailField(blank=True, max_length=254, verbose_name='E-post')),
                ('start', models.DateTimeField(verbose_name='Starttid')),
                ('end', models.DateTimeField(verbose_name='Sluttid')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='Beskrivning')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Skapad')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Bokare')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room', verbose_name='Utrymme')),
            ],
            options={
                'verbose_name': 'Bokning',
                'verbose_name_plural': 'Bokningar',
                'ordering': ('start', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='booking_end_after_start')],
            },
        ),
    ]
