# Generated by Django 6.0.7 on 2026-10-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='code_instructions',
            field=models.TextField(blank=True, help_text='Visas offentligt där koden efterfrågas, i stället för standardtexten. Lämna tomt om standardtexten räcker.', verbose_name='Så får besökare koden'),
        ),
    ]
