# Generated by Django 6.0.7 on 2026-10-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingsettings_code_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsettings',
            name='rotation_period',
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='code_generation',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Räknas upp varje gång koden byts. Koden härleds ur den och kan inte läsas av härifrån.', verbose_name='Kodgeneration'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='rotated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='När koden senast byttes. Gör att den förra koden fungerar en stund till.', null=True, verbose_name='Senast bytt'),
        ),
    ]
