# Generated by Django 6.0.7 on 2026-10-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_bookingsettings_rotation_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsettings',
            name='code_generation',
        ),
        migrations.RemoveField(
            model_name='bookingsettings',
            name='rotated_at',
        ),
        migrations.AddField(
            model_name='room',
            name='code_generation',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Räknas upp varje gång utrymmets kod byts. Koden härleds ur den och kan inte läsas av härifrån.', verbose_name='Kodgeneration'),
        ),
        migrations.AddField(
            model_name='room',
            name='rotated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='När utrymmets kod senast byttes. Gör att den förra koden fungerar en stund till.', null=True, verbose_name='Senast bytt'),
        ),
    ]
