# Generated by Django 6.0.7 on 2026-10-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_bookingsettings_code_generation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
    ]
