# Generated by Django 6.0.7 on 2026-10-03 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_room_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bookable_from',
            field=models.TimeField(blank=True, help_text='Lämna båda tomma för att tillåta bokning dygnet runt. Med tider gäller de varje dag.', null=True, verbose_name='Bokningsbart från'),
        ),
        migrations.AddField(
            model_name='room',
            name='bookable_until',
            field=models.TimeField(blank=True, help_text='En bokning måste börja och sluta inom samma dygn när tider är satta.', null=True, verbose_name='Bokningsbart till'),
        ),
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Stängt från')),
                ('end', models.DateTimeField(verbose_name='Stängt till')),
                ('description', models.CharField(blank=True, help_text='Visas för besökare, till exempel vad som gör att utrymmet är stängt.', max_length=255, verbose_name='Beskrivning')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='booking.room', verbose_name='Utrymme')),
            ],
            options={
                'verbose_name': 'Stängd period',
                'verbose_name_plural': 'Stängda perioder',
                'ordering': ('start', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='closure_end_after_start')],
            },
        ),
    ]
