# Generated by Django 3.1.13 on 2022-08-20 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Val', 'verbose_name_plural': 'Val'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Fråga', 'verbose_name_plural': 'Frågor'},
        ),
        migrations.AddField(
            model_name='question',
            name='end_vote',
            field=models.BooleanField(default=False, verbose_name='Avsluta röstande'),
        ),
        migrations.AddField(
            model_name='question',
            name='members_only',
            field=models.BooleanField(default=False, verbose_name='Endast medlemmar'),
        ),
        migrations.AddField(
            model_name='question',
            name='multiple_choice',
            field=models.BooleanField(default=False, verbose_name='Flerval'),
        ),
        migrations.AddField(
            model_name='question',
            name='ordinary_members_only',
            field=models.BooleanField(default=False, verbose_name='Endast ordinarie medlemmar'),
        ),
        migrations.AddField(
            model_name='question',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publicera'),
        ),
        migrations.AddField(
            model_name='question',
            name='show_results',
            field=models.BooleanField(default=False, verbose_name='Visa resultat'),
        ),
        migrations.AddField(
            model_name='question',
            name='vote_members_only',
            field=models.BooleanField(default=False, verbose_name='Endast röstberättigade medlemmar'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Röstare',
                'verbose_name_plural': 'Röstare',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='voters',
            field=models.ManyToManyField(related_name='voters', through='polls.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
