# Generated by Django 4.2.7 on 2023-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201111_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='members_only',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ordinary_members_only',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vote_members_only',
        ),
        migrations.AddField(
            model_name='question',
            name='required_multiple_choices',
            field=models.IntegerField(blank=True, null=True, verbose_name='Antal flerval som krävs'),
        ),
        migrations.AddField(
            model_name='question',
            name='voting_options',
            field=models.IntegerField(choices=[(1, 'Vem som helst'), (2, 'Endast medlemmar'), (3, 'Endast ordinarie medlemmar'), (4, 'Endast röstberättigade medlemmar')], default=1, verbose_name='Valmöjligheter'),
        ),
    ]
