# Generated by Django 6.0.5 on 2026-05-13 17:37

import django.utils.timezone
from django.db import migrations, models


def migrate_question_publication(apps, schema_editor):
    Question = apps.get_model("polls", "Question")
    for question in Question.objects.all():
        question.published_time = question.pub_date if question.published else None
        question.save(update_fields=["published_time"])


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_backfill_poll_default_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='published_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Lämna tomt för att dölja frågan. Välj en framtida tid för schemalagd publicering.', null=True, verbose_name='Publiceras'),
        ),
        migrations.RunPython(migrate_question_publication, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='question',
            name='published',
        ),
    ]
