"""
Django settings for date project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
# update

import json
import os

import environ
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _

from .dependencies.ckeditor import *  # noqa

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    DEVELOP=(bool, False),
    USE_UNFOLD=(bool, False),
)


_MISSING = object()


def env_alias(name, *aliases, cast=str, default=_MISSING):
    for env_name in (name, *aliases):
        if env_name in os.environ:
            return env(env_name, cast)

    if default is _MISSING:
        return env(name, cast)

    return default


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Quick-date development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_alias('DATE_SECRET_KEY', 'SECRET_KEY', default='SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_alias('DATE_DEBUG', 'DEBUG', cast=bool, default=False)

DEVELOP = env_alias('DATE_DEVELOP', 'DEVELOP', cast=bool, default=False)

USE_UNFOLD = env('USE_UNFOLD', bool, False)


def _get_unfold_sidebar_navigation(request):
    from core.admin_ui import get_sidebar_navigation

    return get_sidebar_navigation(request)


def _get_unfold_site_url(request):
    from django.conf import settings as django_settings

    return getattr(django_settings, "CONTENT_VARIABLES", {}).get("SITE_URL", "/")


_UNFOLD_ENV_LABEL = env("UNFOLD_ENVIRONMENT_LABEL", str, "")
_UNFOLD_ENV_TYPE = env("UNFOLD_ENVIRONMENT_TYPE", str, "")


def _get_unfold_environment(request):
    if _UNFOLD_ENV_LABEL:
        return _UNFOLD_ENV_LABEL, _UNFOLD_ENV_TYPE or "info"

    host = request.get_host().split(":", 1)[0].lower()
    if host.split(".", 1)[0] == "qa":
        return _("Quality Assurance"), _UNFOLD_ENV_TYPE or "warning"

    # Read DEBUG/DEVELOP through settings rather than the module-level globals so
    # tests can override them via @override_settings without depending on env at
    # import time.
    from django.conf import settings as django_settings

    if getattr(django_settings, "DEVELOP", False) or getattr(django_settings, "DEBUG", False):
        return _("Development"), "warning"

    return _("Production"), "success"


UNFOLD = {
    "SITE_URL": _get_unfold_site_url,
    "ENVIRONMENT": _get_unfold_environment,
    "STYLES": [
        lambda request: static("date/css/admin.css"),
    ],
    "SCRIPTS": [
        lambda request: static("date/js/admin_sidebar.js"),
    ],
    "SIDEBAR": {
        "show_search": True,
        "navigation": _get_unfold_sidebar_navigation,
    },
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
}

# This gets set only when tests are ran with date-test command
TEST = env('TEST', bool, False)

ALLOWED_HOSTS = json.loads(env('ALLOWED_HOSTS', str, '[]'))

CSRF_TRUSTED_ORIGINS = json.loads(env('ALLOWED_ORIGINS', str, '[]'))


if not DEVELOP:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

USE_X_FORWARDED_HOST = env('USE_X_FORWARDED_HOST', bool, False)
if env('TRUST_X_FORWARDED_PROTO', bool, False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


def get_installed_apps(proj_apps):
    return [
        'daphne',
        'date',
        'members.apps.MemberConfig',
        'functionaries',
        *proj_apps,
        'modeltranslation',
        *(['unfold', 'unfold.contrib.filters', 'unfold.contrib.forms', 'unfold.contrib.inlines'] if USE_UNFOLD else []),
        'date.apps.DateAdminConfig',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django_otp',
        'django_otp.plugins.otp_static',
        'django_otp.plugins.otp_totp',
        'two_factor',
        'admin_ordering',
        'django_ckeditor_5',
        'channels',
        'storages',
        'django_tables2',
        'django_filters',
        'bootstrap3',
        'django_cleanup',  # Should be places last
    ]


# Common template config
COMMON_TEMPLATE_DIRS = [
    'templates/common',
    'templates/common/members',
]


COMMON_CONTEXT_PROCESSORS = [
    'django.template.context_processors.debug',
    'django.template.context_processors.request',
    'django.template.context_processors.i18n',
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
    'staticpages.context_processors.get_categories',
    'staticpages.context_processors.get_urls',
    'core.context_processors.captcha_context',
    'core.context_processors.apply_content_variables',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'date.middleware.ServerTimingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'date.middleware.LanguageStateMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'date.middleware.LangMiddleware',
    'date.middleware.HTCPCPMiddleware',
]

SERVER_TIMING_ENABLED = DEVELOP


WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.routing.application'


REDIS_SERVER = env("REDIS_SERVER", str, "redis://redis:6379")
CELERY_BROKER_URL = env("CELERY_BROKER_URL", str, "redis://redis:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", str, CELERY_BROKER_URL)

# Acknowledge tasks only after execution and requeue on worker loss, so a
# worker killed mid-task (rollout, node drain, OOM) does not silently drop
# the task. Tasks must tolerate redelivery (emails can be re-sent).
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [REDIS_SERVER],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_DATABASE', str, 'postgres'),
        'USER': env('DB_USERNAME', str, 'postgres'),
        'PASSWORD': env_alias('DATE_DB_PASSWORD', 'DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', str, 'db'),
        'PORT': env('DB_PORT', int, 5432),
        # Keep PostgreSQL connections alive between requests to avoid
        # connection setup latency; must live inside the database config.
        'CONN_MAX_AGE': env('DB_CONN_MAX_AGE', int, 600),
        # Re-verify persistent connections so they survive database restarts.
        'CONN_HEALTH_CHECKS': True,
    }
}

# Caches
# https://docs.djangoproject.com/en/5.2/topics/cache/

# https://docs.djangoproject.com/en/5.2/topics/cache/#dummy-caching-for-development
DUMMY_CACHE = {
    "default": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    }
}

# https://docs.djangoproject.com/en/5.2/topics/cache/#redis
REDIS_CACHE = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_SERVER,
    },
}

CACHES = DUMMY_CACHE if DEVELOP else REDIS_CACHE

# Custom members model
AUTH_USER_MODEL = 'members.Member'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = ('members.backends.AuthBackend',)

LOGIN_URL = 'members:login'
LOGIN_REDIRECT_URL = 'members:info'

# Make CKEditor5 Work with modeltranslations
MODELTRANSLATION_CUSTOM_FIELDS = ('CKEditor5Field',)


def get_staff_groups(default_groups: list):
    """Add extra staff groups from environment variable to default_groups."""
    default_groups.extend(json.loads(os.environ.get('EXTRA_STAFF_GROUPS', '[]')))
    return default_groups


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/


LOCALE_PATHS = ('locale',)

ALL_LANGUAGES = (('sv', ("Svenska")), ('en', ("English")), ('fi', ("Suomi")))

LANGUAGE_CODE = 'sv'
USE_ACCEPT_LANGUAGE_HEADER = False
ENABLE_LANGUAGE_FEATURES = env('ENABLE_LANGUAGE_FEATURES', bool, False)
LANGUAGES = (
    ALL_LANGUAGES
    if ENABLE_LANGUAGE_FEATURES
    else (tuple(language for language in ALL_LANGUAGES if language[0] == LANGUAGE_CODE))
)
# Keep modeltranslation's schema stable regardless of whether the multilingual
# UI is currently enabled. Otherwise makemigrations can think translated fields
# should be removed whenever ENABLE_LANGUAGE_FEATURES is false.
MODELTRANSLATION_LANGUAGES = tuple(code for code, _label in ALL_LANGUAGES)

TIME_ZONE = 'Europe/Helsinki'

USE_I18N = True

USE_TZ = True

DECIMAL_INPUT_FORMATS = ()

DATE_INPUT_FORMATS = ('%d.%m.%Y', '%Y-%m-%d')

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

PROJECT_NAME = os.environ.get("PROJECT_NAME", "date")
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Association capabilities. Prefer these over direct PROJECT_NAME checks in
# application code so a new association can enable behavior via settings.
APRIL_HOMEPAGE_ENABLED = False
REGISTRATION_TERMS_ENABLED = False
EQUALITY_PLAN_ENABLED = False
KK_EVENT_TEMPLATES_ENABLED = False

# The runtime image is built with each association's static collected into
# /code/static-collected/<PROJECT_NAME>; pick that tree when present so every
# variant serves build-time static with no startup collection. Local
# development (no such directory) falls back to the source tree default.
STATIC_ROOT = env_alias(
    'STATIC_ROOT',
    default=(
        f"/code/static-collected/{PROJECT_NAME}"
        if os.path.isdir(f"/code/static-collected/{PROJECT_NAME}")
        else os.path.join(PROJECT_DIR, 'static')
    ),
)

# Cloudflare captcha config
TURNSTILE_SECRET_KEY = env("CF_TURNSTILE_SECRET_KEY", str, "")
CAPTCHA_SITE_KEY = env("CF_TURNSTILE_SITE_KEY", str, "")

# S3 conf using django storages
USE_S3 = env('USE_S3', bool, False)

# Direct browser-to-storage uploads (Uppy) with presigned URLs. Only relevant
# when USE_S3 is enabled: uploads then bypass the web process entirely and go
# straight to the S3-compatible endpoint (e.g. Backblaze B2), with a small
# signing API as the only origin-side step. Off by default; enable per
# deployment once the bucket CORS/lifecycle setup from docs/dev/uploads.md
# is in place.
DIRECT_UPLOADS_ENABLED = env('DIRECT_UPLOADS_ENABLED', bool, False)
# Key prefix for uploads that have not been attached to a model row yet.
# Buckets should expire this prefix (see docs/dev/uploads.md).
DIRECT_UPLOAD_TMP_PREFIX = 'tmp/'

STORAGES = {
    "default": {
        "BACKEND": 'django.core.files.storage.FileSystemStorage',
    },
    "staticfiles": {
        # Content-hashed filenames let browsers cache static assets
        # indefinitely; the manifest is generated by collectstatic.
        "BACKEND": "core.storage_backends.NonStrictManifestStaticFilesStorage",
    },
}

# Serve static from the per-association public S3 bucket (same bucket as
# media, 'static' prefix, CDN via the public custom domain) instead of the
# pod filesystem. Requires a release-time collectstatic upload before the
# flag is enabled on a site.
STATIC_S3_ENABLED = env('STATIC_S3_ENABLED', bool, False)

if USE_S3:
    # aws settings
    AWS_S3_ENDPOINT_URL = env_alias('S3_ENDPOINT_URL', 'AWS_S3_ENDPOINT_URL')
    AWS_ACCESS_KEY_ID = env_alias('S3_ACCESS_KEY', 'AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env_alias('S3_SECRET_KEY', 'AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env_alias('S3_BUCKET_NAME', 'AWS_STORAGE_BUCKET_NAME')
    AWS_PRIVATE_STORAGE_BUCKET_NAME = (
        env_alias(
            'S3_PRIVATE_BUCKET_NAME',
            'AWS_PRIVATE_STORAGE_BUCKET_NAME',
            default='',
        )
        or AWS_STORAGE_BUCKET_NAME
    )
    AWS_PUBLIC_STORAGE_BUCKET_NAME = (
        env_alias(
            'S3_PUBLIC_BUCKET_NAME',
            'AWS_PUBLIC_STORAGE_BUCKET_NAME',
            default='',
        )
        or AWS_STORAGE_BUCKET_NAME
    )
    AWS_S3_REGION_NAME = env_alias('S3_REGION_NAME', 'AWS_S3_REGION_NAME', default=None)
    AWS_S3_SIGNATURE_VERSION = env_alias('S3_SIGNATURE_VERSION', 'AWS_S3_SIGNATURE_VERSION', default=None)
    AWS_S3_ADDRESSING_STYLE = env_alias('S3_ADDRESSING_STYLE', 'AWS_S3_ADDRESSING_STYLE', default=None)
    AWS_S3_PUBLIC_CUSTOM_DOMAIN = (
        env_alias('S3_PUBLIC_CUSTOM_DOMAIN', 'AWS_S3_PUBLIC_CUSTOM_DOMAIN', default='') or None
    )
    AWS_S3_PRIVATE_CUSTOM_DOMAIN = (
        env_alias('S3_PRIVATE_CUSTOM_DOMAIN', 'AWS_S3_PRIVATE_CUSTOM_DOMAIN', default='') or None
    )
    # Optional dedicated CDN domain for static; defaults to the public media
    # domain (both serve the same bucket).
    AWS_S3_STATIC_CUSTOM_DOMAIN = (
        env_alias('S3_STATIC_CUSTOM_DOMAIN', 'AWS_S3_STATIC_CUSTOM_DOMAIN', default='') or None
    )
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600

    # s3 public media settings
    PRIVATE_MEDIA_LOCATION = env('PRIVATE_MEDIA_LOCATION')
    PUBLIC_MEDIA_LOCATION = env('PUBLIC_MEDIA_LOCATION')
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_PRIVATE_STORAGE_BUCKET_NAME}/{PRIVATE_MEDIA_LOCATION}/"

    def get_s3_storage_options(bucket_name, location, querystring_auth, custom_domain=None):
        options = {
            "bucket_name": bucket_name,
            "custom_domain": custom_domain or False,
            "location": location,
            "querystring_auth": querystring_auth,
        }
        if AWS_S3_REGION_NAME:
            options["region_name"] = AWS_S3_REGION_NAME
        if AWS_S3_SIGNATURE_VERSION:
            options["signature_version"] = AWS_S3_SIGNATURE_VERSION
        if AWS_S3_ADDRESSING_STYLE:
            options["addressing_style"] = AWS_S3_ADDRESSING_STYLE
        return options

    STORAGES["default"] = {  # TODO allow setting this to local
        "BACKEND": "core.storage_backends.PrivateMediaStorage",
        "OPTIONS": get_s3_storage_options(
            AWS_PRIVATE_STORAGE_BUCKET_NAME,
            PRIVATE_MEDIA_LOCATION,
            AWS_QUERYSTRING_AUTH,
            AWS_S3_PRIVATE_CUSTOM_DOMAIN,
        )
        | {"querystring_expire": AWS_QUERYSTRING_EXPIRE},
    }
    STORAGES["public_media"] = {
        "BACKEND": "core.storage_backends.PublicMediaStorage",
        "OPTIONS": get_s3_storage_options(
            AWS_PUBLIC_STORAGE_BUCKET_NAME,
            PUBLIC_MEDIA_LOCATION,
            False,
            AWS_S3_PUBLIC_CUSTOM_DOMAIN,
        ),
    }

    if STATIC_S3_ENABLED:
        STORAGES["staticfiles"] = {
            "BACKEND": "core.storage_backends.StaticStorage",
            "OPTIONS": get_s3_storage_options(
                AWS_PUBLIC_STORAGE_BUCKET_NAME,
                "static",
                False,
                AWS_S3_STATIC_CUSTOM_DOMAIN or AWS_S3_PUBLIC_CUSTOM_DOMAIN,
            ),
        }

else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    MEDIA_URL = '/media/'

    # Not in use when not using s3 but need to be set in order not to cause errors
    PRIVATE_MEDIA_LOCATION = 'media/private'
    PUBLIC_MEDIA_LOCATION = 'media/public'
    AWS_STORAGE_BUCKET_NAME = "media"

# Development serves static from the local finders by default; an explicit
# STATIC_S3_ENABLED wins so S3 URLs are used even when DEBUG is on (e.g. CI
# containers inherit DATE_DEBUG from .env).
if DEBUG and not STATIC_S3_ENABLED:
    STORAGES["staticfiles"]["BACKEND"] = "django.contrib.staticfiles.storage.StaticFilesStorage"

STATIC_URL = '/static/'

LOGOUT_REDIRECT_URL = 'index'
OTP_LOGIN_URL = 'members:login'

if DEBUG:
    WHITENOISE_USE_FINDERS = True
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = env('EMAIL_USE_TLS', bool, True)
EMAIL_USE_SSL = env('EMAIL_USE_SSL', bool, False)
EMAIL_HOST = env('EMAIL_HOST', str, '')
EMAIL_HOST_USER = env('EMAIL_HOST_USER', str, '')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', str, '')
EMAIL_PORT = env('EMAIL_PORT', int, 587)

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', str, '')
EMAIL_HOST_RECEIVER = env('EMAIL_HOST_RECEIVER', str, '')

DATA_UPLOAD_MAX_NUMBER_FIELDS = 30000  # large value for large events

ALUMNI_SETTINGS = os.environ.get("ALUMNI_SETTINGS", '')

# GitHub OAuth settings
GITHUB_CLIENT_ID = env('GITHUB_CLIENT_ID', str, '')
GITHUB_CLIENT_SECRET = env('GITHUB_CLIENT_SECRET', str, '')
GITHUB_MFA_POLICY = env('GITHUB_MFA_POLICY', str, 'enrolled').lower()

DEFAULT_EXCEPTION_REPORTER_FILTER = 'core.redaction.DateExceptionReporterFilter'

LOG_LEVEL = env('LOG_LEVEL', str, 'DEBUG' if DEBUG else 'INFO')
DJANGO_LOG_LEVEL = env('DJANGO_LOG_LEVEL', str, 'INFO')
DATE_LOG_LEVEL = env('DATE_LOG_LEVEL', str, LOG_LEVEL)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            '()': 'core.redaction.RedactingFormatter',
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s',
        },
        'simple': {'()': 'core.redaction.RedactingFormatter', 'format': '%(levelname)s %(message)s'},
    },
    'handlers': {
        'console': {'level': 'NOTSET', 'class': 'logging.StreamHandler', 'formatter': 'simple'},
        'console_debug': {'level': 'DEBUG', 'class': 'logging.StreamHandler', 'formatter': 'simple'},
        'console_error': {'level': 'ERROR', 'class': 'logging.StreamHandler', 'formatter': 'verbose'},
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console_error'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django_auth_ldap': {
            'handlers': ['console_debug'],
            'level': DATE_LOG_LEVEL,
            'propagate': True,
        },
        'date': {
            'handlers': ['console_debug'],
            'level': DATE_LOG_LEVEL,
            'propagate': True,
        },
        'daphne': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

EXPERIMENTAL_FEATURES = []

# Re-export every public name so that `from .common import *` in a
# variant settings module brings along imported helpers (os, BASE_DIR,
# COMMON_TEMPLATE_DIRS, etc.) alongside the settings themselves.
__all__ = [name for name in globals() if not name.startswith('_')]
