# Generated by Django 5.0.3 on 2024-04-08 21:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucia', '0002_auto_20201129_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Innehåll'),
        ),
    ]
