# Generated by Django 6.0.5 on 2026-05-13 17:37

from datetime import UTC, datetime

import django.utils.timezone
from django.db import migrations, models


def migrate_candidate_publication(apps, schema_editor):
    Candidate = apps.get_model("lucia", "Candidate")
    published_fallback = datetime(2000, 1, 1, tzinfo=UTC)

    Candidate.objects.filter(published=True).update(published_time=published_fallback)
    Candidate.objects.filter(published=False).update(published_time=None)


class Migration(migrations.Migration):
    dependencies = [
        ("lucia", "0003_alter_candidate_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="published_time",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Lämna tomt för att dölja kandidaten. Välj en framtida tid för schemalagd publicering.",
                null=True,
                verbose_name="Publiceras",
            ),
        ),
        migrations.RunPython(migrate_candidate_publication, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="candidate",
            name="published",
        ),
    ]
