# Generated by Django 5.1 on 2024-08-23 13:43

import django.utils.timezone
import publications.fields
import publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to auto-generate from title', max_length=255, unique=True, verbose_name='Slug')),
                ('file', publications.fields.PublicFileField(upload_to=publications.models.upload_to, verbose_name='File')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('publication_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Publication Date')),
                ('is_public', models.BooleanField(default=True, help_text='If checked, this PDF will be visible to everyone. If unchecked, it will be hidden from all users.', verbose_name='Public Access')),
                ('requires_login', models.BooleanField(default=False, help_text='If checked, users must be logged in to access this PDF', verbose_name='Requires Login')),
            ],
            options={
                'verbose_name': 'PDF File',
                'verbose_name_plural': 'PDF Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
