# Generated by Django 5.1 on 2024-08-16 12:25

import publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to auto-generate from title', max_length=255, unique=True, verbose_name='Slug')),
                ('file', models.FileField(upload_to=publications.models.upload_to, verbose_name='File')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('author', models.CharField(blank=True, max_length=250, verbose_name='Author')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('file_size', models.PositiveIntegerField(editable=False, null=True, verbose_name='File Size (bytes)')),
                ('num_pages', models.PositiveIntegerField(editable=False, null=True, verbose_name='Number of Pages')),
                ('is_public', models.BooleanField(default=False, help_text='If checked, this PDF will be accessible without login', verbose_name='Public Access')),
            ],
            options={
                'verbose_name': 'PDF File',
                'verbose_name_plural': 'PDF Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
