# Generated by Django 6.0.5 on 2026-05-17

import publications.fields
import publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='If set, visitors are sent to this URL instead of the internal PDF viewer.', max_length=500, verbose_name='Redirect URL'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=publications.fields.PublicFileField(blank=True, upload_to=publications.models.upload_to, verbose_name='File'),
        ),
    ]
