# Generated by Django 6.0.5 on 2026-05-17

import publications.fields
import publications.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_pdffile_redirect_url_alter_pdffile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='cover_image',
            field=publications.fields.PublicFileField(blank=True, help_text='Optional thumbnail image shown on the publications list.', upload_to=publications.models.cover_upload_to, verbose_name='Cover image'),
        ),
    ]
