# Generated by Django 6.0.5 on 2026-05-17 11:41

import publications.fields
import publications.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publicationcollection_pdffile_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcollection',
            name='cover_image',
            field=publications.fields.PublicFileField(blank=True, help_text='Optional image shown for this collection on the publications index.', upload_to=publications.models.collection_cover_upload_to, verbose_name='Cover image'),
        ),
    ]
