# Generated by Django 3.0.7 on 2020-11-26 16:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('pub_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Publicerad')),
                ('body', ckeditor.fields.RichTextField(blank=True, verbose_name='Innehåll')),
            ],
        ),
    ]
