# Generated by Django 4.2.1 on 2023-05-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200109_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniEmailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=256)),
            ],
        ),
    ]
