# Generated by Django 4.2.2 on 2023-06-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alumniemailrecipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumniemailrecipient',
            options={'verbose_name': 'Emailmottagare för ARG', 'verbose_name_plural': 'Emailmottagare för ARG'},
        ),
    ]
