# Generated by Django 2.1.1 on 2018-09-12 10:53

import archive.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Namn')),
                ('file', models.FileField(upload_to=archive.models.upload_to)),
            ],
            options={
                'verbose_name': 'fil',
                'verbose_name_plural': 'filer',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Namn')),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Samling',
                'verbose_name_plural': 'Samlingar',
            },
        ),
        migrations.AddField(
            model_name='abstractfile',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Collection', verbose_name='Samling'),
        ),
    ]
