# Generated by Django 2.1.1 on 2018-09-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractfile',
            name='file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
