# Generated by Django 3.1.13 on 2022-08-20 18:02

import archive.fields
import archive.models
import core.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20200109_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
            ],
            options={
                'verbose_name': 'Dokumentarkiv',
                'verbose_name_plural': 'Dokumentarkiv',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('archive.collection',),
        ),
        migrations.CreateModel(
            name='PictureCollection',
            fields=[
            ],
            options={
                'verbose_name': 'Bildarkiv',
                'verbose_name_plural': 'Bildarkiv',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('archive.collection',),
        ),
        migrations.CreateModel(
            name='PublicCollection',
            fields=[
            ],
            options={
                'verbose_name': 'Offentliga Filer',
                'verbose_name_plural': 'Offentliga Filer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('archive.collection',),
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'dokument', 'verbose_name_plural': 'dokument'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('Pictures', 'Bilder'), ('Documents', 'Dokument'), ('PublicFiles', 'OffentligaFiler')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.collection', verbose_name='Samling'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=archive.models.upload_to, verbose_name='Filnamn'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Namn'),
        ),
        migrations.CreateModel(
            name='PublicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_file', archive.fields.PublicFileField(storage=core.storage_backends.PublicMediaStorage(), upload_to=archive.models.upload_to, verbose_name='file')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.collection', verbose_name='Galleri')),
            ],
            options={
                'verbose_name': 'fil',
                'verbose_name_plural': 'filer',
            },
        ),
    ]
