# Generated by Django 2.1.1 on 2018-09-11 06:13

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20180911_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractfile',
            name='file',
            field=models.FileField(upload_to=archive.models.upload_to),
        ),
    ]
