# Generated by Django 3.1.13 on 2022-11-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20220820_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCollection',
            fields=[
            ],
            options={
                'verbose_name': 'Tentarkiv',
                'verbose_name_plural': 'Tentarkiv',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('archive.collection',),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('Pictures', 'Bilder'), ('Documents', 'Dokument'), ('Exams', 'Tenter'), ('PublicFiles', 'OffentligaFiler')], max_length=20),
        ),
    ]
