# Generated by Django 3.1.12 on 2021-08-01 15:15

import archive.fields
import archive.models
import core.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20200716_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCollection',
            fields=[
            ],
            options={
                'verbose_name': 'Offentliga Filer',
                'verbose_name_plural': 'Offentliga Filer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('archive.collection',),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('Pictures', 'Bilder'), ('Documents', 'Dokument'), ('PublicFiles', 'OffentligaFiler')], max_length=20),
        ),
        migrations.CreateModel(
            name='PublicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_file', archive.fields.PublicFileField(storage=core.storage_backends.PublicMediaStorage(), upload_to=archive.models.upload_to, verbose_name='file')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.collection', verbose_name='Galleri')),
            ],
            options={
                'verbose_name': 'fil',
                'verbose_name_plural': 'filer',
            },
        ),
    ]
