# Generated by Django 5.0.9 on 2025-03-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20221110_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='hide_for_gulis',
            field=models.BooleanField(default=False, verbose_name='Göm för gulisar'),
        ),
    ]
