# Generated by Django 5.2.12 on 2026-04-07 17:40

import archive.models
import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20221004_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfile',
            name='some_file',
            field=core.fields.PublicFileField(upload_to=archive.models.upload_to, verbose_name='file'),
        ),
    ]
