# Generated by Django 5.2.12 on 2026-04-20 12:21

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_alter_publicfile_some_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='picture',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=32),
        ),
        migrations.AddField(
            model_name='picture',
            name='temp_upload_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='picture',
            name='upload_provider',
            field=models.CharField(choices=[('local', 'Local'), ('s3_direct', 'S3 direct')], default='local', max_length=32),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=archive.models.upload_to),
        ),
    ]
