# Generated by Django 5.2.12 on 2026-05-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_alter_publicfile_some_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Om angiven skickas besökaren vidare hit när albumet öppnas.', max_length=500, verbose_name='Omdirigeringsadress'),
        ),
        migrations.AddField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Valfri bild som visas som albumets miniatyr.', upload_to='archive/thumbnails/', verbose_name='Albumminiatyr'),
        ),
    ]
