# Generated by Django 6.0.5 on 2026-05-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_alter_publicfile_some_file'),
        ('exambank', '0002_copy_archive_exams'),
        ('gallery', '0002_copy_archive_pictures'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='picture',
                    name='collection',
                ),
                migrations.DeleteModel(
                    name='ExamCollection',
                ),
                migrations.DeleteModel(
                    name='PictureCollection',
                ),
                migrations.AlterField(
                    model_name='collection',
                    name='type',
                    field=models.CharField(choices=[('Documents', 'Dokument'), ('PublicFiles', 'OffentligaFiler')], max_length=20),
                ),
                migrations.DeleteModel(
                    name='Picture',
                ),
            ],
            database_operations=[],
        ),
    ]
