# Generated by Django 5.2.12 on 2026-04-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_picture_upload_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='temp_upload_key',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
    ]
