# Generated by Django 5.2.12 on 2026-04-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_temp_upload_key_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='temp_upload_key',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, unique=True),
        ),
    ]
