<<<<<<< HEAD
# Generated by Django 3.0.7 on 2020-09-16 13:26
=======
# Generated by Django 3.0.7 on 2020-10-22 12:14
>>>>>>> develop

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IgUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('shortcode', models.CharField(max_length=255, verbose_name='SHORTCODE')),
            ],
        ),
    ]
