# Generated by Django 6.0.5 on 2026-05-11 18:44

from django.core.management.color import no_style
from django.db import migrations


def reset_sequences(apps, schema_editor, models):
    sql_statements = schema_editor.connection.ops.sequence_reset_sql(no_style(), models)
    with schema_editor.connection.cursor() as cursor:
        for statement in sql_statements:
            cursor.execute(statement)


def copy_social_models(apps, schema_editor):
    OldIgUrl = apps.get_model("social", "IgUrl")
    OldHarassment = apps.get_model("social", "Harassment")
    OldHarassmentEmailRecipient = apps.get_model("social", "HarassmentEmailRecipient")
    NewIgUrl = apps.get_model("instagram", "IgUrl")
    NewHarassment = apps.get_model("harassment", "Harassment")
    NewHarassmentEmailRecipient = apps.get_model("harassment", "HarassmentEmailRecipient")

    for ig_url in OldIgUrl.objects.all().iterator():
        NewIgUrl.objects.update_or_create(
            id=ig_url.id,
            defaults={
                "url": ig_url.url,
                "shortcode": ig_url.shortcode,
            },
        )

    for harassment in OldHarassment.objects.all().iterator():
        NewHarassment.objects.update_or_create(
            id=harassment.id,
            defaults={
                "email": harassment.email,
                "message": harassment.message,
            },
        )

    for recipient in OldHarassmentEmailRecipient.objects.all().iterator():
        NewHarassmentEmailRecipient.objects.update_or_create(
            id=recipient.id,
            defaults={
                "recipient_email": recipient.recipient_email,
            },
        )

    reset_sequences(apps, schema_editor, [NewIgUrl, NewHarassment, NewHarassmentEmailRecipient])


def restore_social_models(apps, schema_editor):
    OldIgUrl = apps.get_model("social", "IgUrl")
    OldHarassment = apps.get_model("social", "Harassment")
    OldHarassmentEmailRecipient = apps.get_model("social", "HarassmentEmailRecipient")
    NewIgUrl = apps.get_model("instagram", "IgUrl")
    NewHarassment = apps.get_model("harassment", "Harassment")
    NewHarassmentEmailRecipient = apps.get_model("harassment", "HarassmentEmailRecipient")

    for ig_url in NewIgUrl.objects.all().iterator():
        OldIgUrl.objects.update_or_create(
            id=ig_url.id,
            defaults={
                "url": ig_url.url,
                "shortcode": ig_url.shortcode,
            },
        )

    for harassment in NewHarassment.objects.all().iterator():
        OldHarassment.objects.update_or_create(
            id=harassment.id,
            defaults={
                "email": harassment.email,
                "message": harassment.message,
            },
        )

    for recipient in NewHarassmentEmailRecipient.objects.all().iterator():
        OldHarassmentEmailRecipient.objects.update_or_create(
            id=recipient.id,
            defaults={
                "recipient_email": recipient.recipient_email,
            },
        )

    reset_sequences(apps, schema_editor, [OldIgUrl, OldHarassment, OldHarassmentEmailRecipient])


class Migration(migrations.Migration):
    dependencies = [
        ("harassment", "0001_initial"),
        ("instagram", "0001_initial"),
        ("social", "0003_harassmentemailrecipient"),
    ]

    operations = [
        migrations.RunPython(copy_social_models, restore_social_models),
        migrations.DeleteModel(
            name="Harassment",
        ),
        migrations.DeleteModel(
            name="HarassmentEmailRecipient",
        ),
        migrations.DeleteModel(
            name="IgUrl",
        ),
    ]
