# Generated by Django 6.1.1 on 2026-10-06 15:31

import core.fields
import django.core.validators
import instagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igurl',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='igurl',
            name='image',
            field=core.fields.PublicFileField(blank=True, upload_to='instagram/', validators=[django.core.validators.validate_image_file_extension, instagram.models.validate_image_height], verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='igurl',
            name='shortcode',
            field=models.CharField(help_text='Klistra in länken till inlägget, t.ex. https://www.instagram.com/p/ABC123/.', max_length=255, verbose_name='Instagram-inlägg'),
        ),
        migrations.AlterField(
            model_name='igurl',
            name='url',
            field=models.CharField(blank=True, help_text='Fylls i av Instagram-uppdateraren. Lämna tomt när du laddar upp en bild.', max_length=255, verbose_name='URL'),
        ),
    ]
