# Generated by Django 2.1 on 2018-08-15 13:39

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-postadress')),
                ('first_name', models.CharField(max_length=30, verbose_name='Förnamn')),
                ('last_name', models.CharField(max_length=30, verbose_name='Efternamn')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefonnummer')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Födelsedag')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Adress')),
                ('zip_code', models.CharField(blank=True, max_length=5, verbose_name='Postkod')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='Postanstalt')),
                ('country', models.CharField(blank=True, default='Finland', max_length=30, verbose_name='Land')),
                ('language', models.CharField(choices=[('sv_FI', 'Svenska'), ('fi-fi', 'Finska')], default='sv_fi', max_length=8, verbose_name='Språk')),
                ('show_email', models.BooleanField(default=False, verbose_name='Visa e-postadress')),
                ('show_phone', models.BooleanField(default=False, verbose_name='Visa telefonnummer')),
                ('role', models.IntegerField(choices=[(1, 'Medlem'), (2, 'Författare'), (3, 'Moderator'), (4, 'Administratör')], default=1, verbose_name='Roll')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='SuperAdmin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'medlem',
                'verbose_name_plural': 'medlemmar',
                'ordering': ('id',),
            },
            managers=[
                ('objects', members.models.MemberManager()),
            ],
        ),
    ]
