# Generated by Django 2.1 on 2018-08-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_staff',
        ),
    ]
