# Generated by Django 2.1 on 2018-08-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('sv-fi', 'Svenska'), ('fi-fi', 'Finska')], default='sv_fi', max_length=8, verbose_name='Språk'),
        ),
    ]
