# Generated by Django 5.0.9 on 2025-03-09 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200109_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniEmailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=256)),
            ],
            options={
                'verbose_name': 'Emailmottagare för ARG',
                'verbose_name_plural': 'Emailmottagare för ARG',
            },
        ),
        migrations.CreateModel(
            name='AlumniSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('year_of_admission', models.IntegerField(null=True)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('work_title', models.CharField(blank=True, max_length=200)),
                ('tfif_membership', models.CharField(blank=True, max_length=50)),
                ('alumni_newsletter_consent', models.BooleanField(default=False)),
                ('operation', models.CharField(blank=True, max_length=200)),
                ('signup_date', models.DateTimeField(auto_now_add=True, verbose_name='Registreringsdatum')),
                ('acknowledge', models.BooleanField(default=False, verbose_name='Processerad')),
            ],
            options={
                'verbose_name': 'Alumnregistrering',
                'verbose_name_plural': 'Alumnregistreringar',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FunctionaryRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('board', models.BooleanField(default=False, verbose_name='Styrelse')),
            ],
            options={
                'verbose_name': 'Funktionärspost',
                'verbose_name_plural': 'Funktionärsposter',
            },
        ),
        migrations.CreateModel(
            name='Functionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Årtal')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('functionary_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.functionaryrole')),
            ],
            options={
                'verbose_name': 'Funktionär',
                'verbose_name_plural': 'Funktionärer',
            },
        ),
    ]
