# Generated by Django 5.0.3 on 2024-04-08 18:36

from datetime import date

from django.db import (migrations)

TARGET_TIME = date(2024, 9, 30)


def create_temp_subscription(apps, schema_editor):
    Subscription = apps.get_model('members', 'Subscription')  # noqa
    Member = apps.get_model('members', 'Member')  # noqa
    SubscriptionPayment = apps.get_model('members', 'SubscriptionPayment')  # noqa

    exp_days = (TARGET_TIME - date.today()).days

    temp_subscription = Subscription.objects.create(
        name="temp-migration-subscription",
        does_expire=True,
        price=0.0,
        renewal_scale='Dagar',
        renewal_period=exp_days
    )

    for member in Member.objects.filter(is_active=True):
        SubscriptionPayment.objects.create(
            member=member,
            subscription=temp_subscription,
            date_paid=date.today(),
            amount_paid=0.0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200109_1909'),
    ]

    operations = [
        migrations.RunPython(create_temp_subscription),
    ]
