# Generated by Django 5.0.14 on 2025-10-31 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionaryRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('board', models.BooleanField(default=False, verbose_name='Styrelse')),
            ],
            options={
                'verbose_name': 'Funktionärspost',
                'verbose_name_plural': 'Funktionärsposter',
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Namn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('permission_profile', models.IntegerField(choices=[(1, 'Gulnäbb'), (2, 'Ordinarie medlem'), (3, 'Stödjande medlem'), (4, 'Seniormedlem')], default=1, verbose_name='Behörighetsprofil')),
            ],
            options={
                'verbose_name': 'Medlemskap',
                'verbose_name_plural': 'medlemskapstyper',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='member',
            name='year_of_admission',
            field=models.IntegerField(blank=True, null=True, verbose_name='Inskrivningsår'),
        ),
        migrations.CreateModel(
            name='Functionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Årtal')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('functionary_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.functionaryrole')),
            ],
            options={
                'verbose_name': 'Funktionär',
                'verbose_name_plural': 'Funktionärer',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.membershiptype'),
        ),
    ]
