# Generated by Django 4.2.4 on 2023-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_alumniemailrecipient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('year_of_admission', models.IntegerField(null=True)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('work_title', models.CharField(blank=True, max_length=200)),
                ('tfif_membership', models.CharField(blank=True, max_length=50)),
                ('alumni_newsletter_consent', models.BooleanField(default=False)),
                ('signup_date', models.DateTimeField(auto_now_add=True, verbose_name='Registreringsdatum')),
                ('acknowledge', models.BooleanField(default=False, verbose_name='Processerad')),
            ],
            options={
                'verbose_name': 'Alumnregistrering',
                'verbose_name_plural': 'Alumnregistreringar',
                'ordering': ('id',),
            },
        ),
    ]
