# Generated by Django 5.0.14 on 2025-10-31 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_grant_one_year_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Namn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('permission_profile', models.IntegerField(choices=[(1, 'Gulnäbb'), (2, 'Ordinarie medlem'), (3, 'Stödjande medlem'), (4, 'Seniormedlem')], default=1, verbose_name='Behörighetsprofil')),
            ],
            options={
                'verbose_name': 'Medlemskap',
                'verbose_name_plural': 'medlemskapstyper',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='AlumniEmailRecipient',
        ),
        migrations.DeleteModel(
            name='AlumniSignUp',
        ),
        migrations.AddField(
            model_name='member',
            name='year_of_admission',
            field=models.IntegerField(blank=True, null=True, verbose_name='Inskrivningsår'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.membershiptype'),
        ),
    ]
