# Generated by Django 4.2.7 on 2023-11-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alumnisignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionaryRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('board', models.BooleanField(default=False, verbose_name='Styrelse')),
            ],
            options={
                'verbose_name': 'Funktionärsroll',
                'verbose_name_plural': 'Funktionärsroller',
            },
        ),
        migrations.CreateModel(
            name='Functionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Årtal')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('functionary_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.functionaryrole')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funktionär',
                'verbose_name_plural': 'Funktionärer',
            },
        ),
    ]
