# Generated by Django 5.0.3 on 2024-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alumnisignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnisignup',
            name='operation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
