# Generated by Django 5.0.10 on 2024-12-09 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alumnisignup_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionaryRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('board', models.BooleanField(default=False, verbose_name='Styrelse')),
            ],
            options={
                'verbose_name': 'Funktionärspost',
                'verbose_name_plural': 'Funktionärsposter',
            },
        ),
        migrations.CreateModel(
            name='Functionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Årtal')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('functionary_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.functionaryrole')),
            ],
            options={
                'verbose_name': 'Funktionär',
                'verbose_name_plural': 'Funktionärer',
            },
        ),
    ]
