# Generated by Django 5.2 on 2025-04-15 10:28

import django.db.models.deletion
from django.db import migrations, models

def create_default_membership_type(apps, _):
    from members.models import PERMISSION_PROFILES

    MembershipType = apps.get_model('members', 'MembershipType')  # noqa

    for profile in PERMISSION_PROFILES:
        MembershipType.objects.get_or_create(
            name=profile[1],
            description='',
            permission_profile=profile[0]
        )

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alumnisignup_operation'),
    ]


    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Namn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('permission_profile', models.IntegerField(choices=[(1, 'Gulnäbb'), (2, 'Ordinarie medlem'), (3, 'Stödjande medlem'), (4, 'Seniormedlem')], default=1, verbose_name='Behörighetsprofil')),
            ],
            options={
                'verbose_name': 'Medlemskap',
                'verbose_name_plural': 'medlemskapstyper',
                'ordering': ('id',),
            },
        ),
        migrations.RunPython(create_default_membership_type),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.membershiptype'),
        ),
    ]
