# Generated by Django 5.2 on 2025-04-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_membershiptype_alter_member_membership_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniEmailRecipient',
        ),
        migrations.DeleteModel(
            name='AlumniSignUp',
        ),
    ]
