# Generated by Django 5.2 on 2025-05-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_year_of_admission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniEmailRecipient',
        ),
        migrations.DeleteModel(
            name='AlumniSignUp',
        ),
    ]
