# Generated by Codex on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_delete_alumniemailrecipient_delete_alumnisignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='two_factor_enabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2FA aktiverad'),
        ),
        migrations.AddField(
            model_name='member',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=64, verbose_name='2FA-hemlighet'),
        ),
    ]
