# Generated by Django 5.2.12 on 2026-04-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_delete_alumniemailrecipient_delete_alumnisignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='github_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='GitHub ID'),
        ),
    ]
