# Generated by Django 4.2.7 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_delete_alumniemailrecipient_delete_alumnisignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionaryrole',
            name='tutor',
            field=models.BooleanField(default=False, verbose_name='Tutor'),
        ),
    ]

