# Generated by Django 6.0.5 on 2026-05-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_functionary_name_alter_functionary_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionaryrole',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='functionaryrole',
            name='title_fi',
            field=models.CharField(max_length=200, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='functionaryrole',
            name='title_sv',
            field=models.CharField(max_length=200, null=True, verbose_name='Titel'),
        ),
    ]
