# Generated by Django 6.0.5 on 2026-05-11 18:44

from django.core.management.color import no_style
from django.db import migrations


def reset_sequences(apps, schema_editor, models):
    sql_statements = schema_editor.connection.ops.sequence_reset_sql(no_style(), models)
    with schema_editor.connection.cursor() as cursor:
        for statement in sql_statements:
            cursor.execute(statement)


def copy_functionaries(apps, schema_editor):
    OldFunctionaryRole = apps.get_model('members', 'FunctionaryRole')
    OldFunctionary = apps.get_model('members', 'Functionary')
    NewFunctionaryRole = apps.get_model('functionaries', 'FunctionaryRole')
    NewFunctionary = apps.get_model('functionaries', 'Functionary')

    for role in OldFunctionaryRole.objects.all().iterator():
        NewFunctionaryRole.objects.update_or_create(
            id=role.id,
            defaults={
                'title': role.title,
                'board': role.board,
            },
        )

    for functionary in OldFunctionary.objects.all().iterator():
        NewFunctionary.objects.update_or_create(
            id=functionary.id,
            defaults={
                'member_id': functionary.member_id,
                'name': functionary.name,
                'functionary_role_id': functionary.functionary_role_id,
                'year': functionary.year,
                'created_date': functionary.created_date,
                'modified_date': functionary.modified_date,
            },
        )

    reset_sequences(apps, schema_editor, [NewFunctionaryRole, NewFunctionary])


def restore_functionaries(apps, schema_editor):
    OldFunctionaryRole = apps.get_model('members', 'FunctionaryRole')
    OldFunctionary = apps.get_model('members', 'Functionary')
    NewFunctionaryRole = apps.get_model('functionaries', 'FunctionaryRole')
    NewFunctionary = apps.get_model('functionaries', 'Functionary')

    for role in NewFunctionaryRole.objects.all().iterator():
        OldFunctionaryRole.objects.update_or_create(
            id=role.id,
            defaults={
                'title': role.title,
                'board': role.board,
            },
        )

    for functionary in NewFunctionary.objects.all().iterator():
        OldFunctionary.objects.update_or_create(
            id=functionary.id,
            defaults={
                'member_id': functionary.member_id,
                'name': functionary.name,
                'functionary_role_id': functionary.functionary_role_id,
                'year': functionary.year,
                'created_date': functionary.created_date,
                'modified_date': functionary.modified_date,
            },
        )

    reset_sequences(apps, schema_editor, [OldFunctionaryRole, OldFunctionary])


class Migration(migrations.Migration):

    dependencies = [
        ('functionaries', '0001_initial'),
        ('members', '0013_functionary_name_alter_functionary_member'),
    ]

    operations = [
        migrations.RunPython(copy_functionaries, restore_functionaries),
        migrations.RemoveField(
            model_name='functionary',
            name='functionary_role',
        ),
        migrations.RemoveField(
            model_name='functionary',
            name='member',
        ),
        migrations.DeleteModel(
            name='FunctionaryRole',
        ),
        migrations.DeleteModel(
            name='Functionary',
        ),
    ]
