# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0015_remove_functionary_functionary_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='archive_access_eligible',
            field=models.BooleanField(default=False, verbose_name='Gulispass utfört'),
        ),
    ]
