# Generated by Django 6.0.7 on 2026-09-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_member_archive_access_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='permission_profile',
            field=models.IntegerField(choices=[(1, 'Gulnäbb'), (2, 'Ordinarie medlem'), (3, 'Stödjande medlem'), (4, 'Seniormedlem'), (5, 'Medlem utan rösträtt')], default=1, verbose_name='Behörighetsprofil'),
        ),
    ]
