# Generated by Django 6.1.1 on 2026-10-04 18:40

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import django_otp.util
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0006_remove_question_published_question_published_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Beskrivning')),
                ('start_datetime', models.DateTimeField(verbose_name='Starttid')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Sluttid')),
                ('allow_non_members', models.BooleanField(default=False, verbose_name='Tillåt icke-medlemmar att delta')),
                ('code_secret', models.CharField(default=django_otp.util.random_hex, verbose_name='Kodens genereringsnyckel')),
                ('code_validity_time', models.SmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kodens giltighetsperiod (sekunder)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'närvaroevenemang',
                'verbose_name_plural': 'närvaroevenemang',
            },
        ),
        migrations.CreateModel(
            name='AttendancePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='attendance.attendanceevent', verbose_name='Närvaroevenemang')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_poll', to='polls.question', verbose_name='Fråga')),
            ],
            options={
                'verbose_name': 'närvarokrav',
                'verbose_name_plural': 'närvarokrav',
            },
        ),
        migrations.CreateModel(
            name='NonMemberAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Namn')),
            ],
            options={
                'verbose_name': 'deltagare, icke-medlem',
                'verbose_name_plural': 'deltagare, icke-medlemmar',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_non_member_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tidpunkt')),
                ('type', models.IntegerField(choices=[(0, 'Anlände'), (1, 'Lämnade')], verbose_name='Typ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Användare')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_changes', to='attendance.attendanceevent', verbose_name='Närvaroevenemang')),
                ('non_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.nonmemberattendee', verbose_name='Icke-medlem')),
            ],
            options={
                'verbose_name': 'närvaroändring',
                'verbose_name_plural': 'närvaroändringar',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('non_member__isnull', True)), models.Q(('user__isnull', True), ('non_member__isnull', False)), _connector='OR'), name='foreign_keys_ok', violation_error_message="Exakt en av 'Användare' eller 'Icke-medlem' måste anges.")],
            },
        ),
    ]
