# Generated by Django 5.2.11 on 2026-02-24 19:41

import attendance.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('start_datetime', models.DateTimeField(verbose_name='Start date/time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End date/time')),
                ('secret', models.CharField(default=attendance.models.generate_event_secret, verbose_name='Secret')),
                ('allow_non_members', models.BooleanField(default=True, verbose_name='Allow non-member attendees')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='NonMemberAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('type', models.IntegerField(choices=[(0, 'Entered'), (1, 'Left')], verbose_name='Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_changes', to='attendance.attendanceevent')),
                ('non_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.nonmemberattendee')),
            ],
            options={
                'get_latest_by': 'timestamp',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('non_member__isnull', True)), models.Q(('user__isnull', True), ('non_member__isnull', False)), _connector='OR'), name='foreign_keys_ok', violation_error_message='One and only one of user or non_member must be set')],
            },
        ),
    ]
