# Generated by Django 6.1.1 on 2026-10-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('polls', '0006_remove_question_published_question_published_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='attendance.attendanceevent', verbose_name='Närvaroevenemang')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_poll', to='polls.question', verbose_name='Fråga')),
            ],
            options={
                'verbose_name': 'närvarokrav',
                'verbose_name_plural': 'närvarokrav',
            },
        ),
    ]
