# Generated by Django 5.2.12 on 2026-04-24 18:26

import django_otp.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceevent',
            name='secret',
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='code_secret',
            field=models.CharField(default=django_otp.util.random_hex, verbose_name='Code generation secret'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='code_validity_time',
            field=models.SmallIntegerField(default=30, verbose_name='Code validity time (seconds)'),
        ),
    ]
