# Generated by Django 6.1.1 on 2026-10-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancepoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='allow_non_members',
            field=models.BooleanField(default=False, verbose_name='Tillåt icke-medlemmar att delta'),
        ),
    ]
