# Generated by Django 5.2.12 on 2026-04-28 16:34

import django.db.models.deletion
import django.utils.timezone
import django_otp.util
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendanceevent_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancechange',
            options={'get_latest_by': 'timestamp', 'verbose_name': 'närvaroändring', 'verbose_name_plural': 'närvaroändingar'},
        ),
        migrations.AlterModelOptions(
            name='attendanceevent',
            options={'verbose_name': 'närvaroevenemang', 'verbose_name_plural': 'närvaroevenemang'},
        ),
        migrations.AlterModelOptions(
            name='nonmemberattendee',
            options={'verbose_name': 'deltagare, icke-medlem', 'verbose_name_plural': 'deltagare, icke-medlemmar'},
        ),
        migrations.AlterField(
            model_name='attendancechange',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_changes', to='attendance.attendanceevent', verbose_name='Närvaroevenemang'),
        ),
        migrations.AlterField(
            model_name='attendancechange',
            name='non_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.nonmemberattendee', verbose_name='Icke-medlem'),
        ),
        migrations.AlterField(
            model_name='attendancechange',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tidpunkt'),
        ),
        migrations.AlterField(
            model_name='attendancechange',
            name='type',
            field=models.IntegerField(choices=[(0, 'Anlände'), (1, 'Lämnade')], verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='attendancechange',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Användare'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='allow_non_members',
            field=models.BooleanField(default=True, verbose_name='Tillåt icke-medlemmar att delta'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='code_secret',
            field=models.CharField(default=django_otp.util.random_hex, verbose_name='Kodens genereringnyckel'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='code_validity_time',
            field=models.SmallIntegerField(default=30, verbose_name='Kodens giltighetsperiod (sekunder)'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beskrivning'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sluttid'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Starttid'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='nonmemberattendee',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Namn'),
        ),
        migrations.AlterConstraint(
            model_name='attendancechange',
            name='foreign_keys_ok',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('non_member__isnull', True)), models.Q(('user__isnull', True), ('non_member__isnull', False)), _connector='OR'), name='foreign_keys_ok', violation_error_message="Exakt en av 'Användare' eller 'Icke-medlem' måste anges."),
        ),
    ]
