# Generated by Django 6.1.1 on 2026-10-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_prepare_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancechange',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name': 'närvaroändring', 'verbose_name_plural': 'närvaroändringar'},
        ),
    ]
