# Generated by Django 6.1.1 on 2026-10-04 18:07

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendanceevent_allow_non_members'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nonmemberattendee',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_non_member_name_ci'),
        ),
    ]
