# Generated by Django 6.1.1 on 2026-10-03 23:11

import django.core.validators
import django_otp.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancechange_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='code_secret',
            field=models.CharField(default=django_otp.util.random_hex, verbose_name='Kodens genereringsnyckel'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='code_validity_time',
            field=models.SmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kodens giltighetsperiod (sekunder)'),
        ),
    ]
