# Generated by Django 6.1.1 on 2026-10-04 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancechange_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='code_validity_time',
            field=models.SmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kodens giltighetsperiod (sekunder)'),
        ),
    ]
