on:
  push:
    branches:
      - develop
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:
    concurrency:
      group: 'docker-publish-${{ github.ref_name }}'
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Convert github.repo to lower
        id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      - name: Docker login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker build
        run: |
          docker buildx create --use
          docker buildx build --push --platform=linux/amd64,linux/arm64 -t ghcr.io/${{ steps.string.outputs.lowercase }}:${{ github.ref_name }} .
